
services:

  server:
    build: ./Docker/apache
    container_name: bauru_jobs_apache_container
    restart: "no"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html/project
      - ./Docker/apache/config/default_symfony.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./Docker/apache/config/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
    depends_on:
      - php
      - database

  php:
    build: ./Docker/php/
    container_name: bauru_jobs_php_container
    user: razielrodrigues:razielrodrigues 
    restart: "no"
    volumes:
      -  ./:/var/www/html/project
      - ./Docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./Docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    
  database:
    image: mariadb:10.5.22
    hostname: docker-mariadb #needed for connection from php-pdo
    container_name: bauru_jobs_mariadb_container
    restart: "no"
    ports:
      - "3306:3306"
    env_file:
      - ./Docker/.env
    volumes:
      - database_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  mail:
    image: mailhog/mailhog:latest
    container_name: bauru_jobs_mail
    restart: "no"
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  database_data:
  mercure_data:
  mercure_config: